version: '3.7'

services:

  web:
    container_name: react-kanopy
    stdin_open: true
    tty: true
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - 7800:8080
    environment:
      - CHOKIDAR_USEPOLLING=true